export { Animation } from "./Animation"
export { Deletion } from "./Deletion"
export { Label } from "./Label"
export { LabelBgColor } from "./LabelBgColor"
export { LabelColor } from "./LabelColor"
export { StrokeColor } from "./StrokeColor"
export { Type } from "./Type"
